[package]
name = "pristine-config"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Pristine configuration management"

[dependencies]
pristine-core = { path = "../pristine-core" }
figment.workspace = true
serde.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
